# Generated by Django 4.0 on 2022-01-29 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+91 (123) 456-7890', max_length=15, validators=[django.core.validators.RegexValidator(message='Must include the country code with the plus sign followed by your phone number.', regex='/^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$/gm')]),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='43701', max_length=5, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats from 00000 to 99999', regex='^\\d{5}$')]),
        ),
    ]
